# 行列積

以下のような行列A、Bを考えます。

$$
A = \left[\begin{array}{c}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{array}\right], 
B = \left[\begin{array}{c}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{array}\right]
$$

NumPyで表すと次のようになります。

In [25]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


## 【問題1】行列積を手計算する
AとBの行列積を手計算で解いてください。


計算過程もマークダウンテキストを用いて説明してください。

$$
AB = \left[\begin{array}{c}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9 \\
\end{array}\right]
\left[\begin{array}{c}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1 \\
\end{array}\right]\
=
\left[\begin{array}{c}
(-1)×0+2×0+3×2 & (-1)×2+2×2+3×9 & (-1)×1+2×(-8)+3×(-1) \\
4×0+(-5)×0+6×2 & 4×2+(-5)×2+6×9 & 4×1+(-5)×(-8)+6×(-1) \\
7×0+8×0+(-9)×2 & 7×2+8×2+(-9)×9 & 7×1+8×(-8)+(-9)×(-1) \\
\end{array}\right]
=
\left[\begin{array}{c}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48 \\
\end{array}\right]
$$


## 【問題2】NumPyの関数による計算
この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。

《3種類の違い》


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

In [26]:
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [27]:
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [28]:
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

## 【問題3】ある要素の計算を実装
手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


1.行列Aの(0,0)の要素a0,0と行列Bの(0,0)の要素b0,0を掛け合わせる

2.行列Aの(0,1)の要素a0,1と行列Bの(1,0)の要素b1,0を掛け合わせる

3.行列Aの(0,2)の要素a0,2と行列Bの(2,0)の要素b2,0を掛け合わせる

4.それらの値を全て足し合わせる


数式で表すと

$$
\sum_{k=0}^{2}a_{0,k}b_{k,0}
$$

です。


この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [29]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


In [30]:
a_ndarray[0,:]

array([-1,  2,  3])

In [31]:
b_ndarray[:, 0]

array([0, 0, 2])

In [32]:
sum = 0
for k in range(3):
    a0k = a_ndarray[0][k]
    b0k = b_ndarray[k][0]
    sum += a0k*b0k
print(sum)

6


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である3×3の行列Cの各要素 ci,jは数式で表すと次のようになります。

$$
c_{i,j}=\sum_{k=0}^{2}a_{i,k}b_{k,j}
$$

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックスiやjを1増やすと、次の行や列に移ることができます。

In [33]:
def cal_dot(a_ndarray, b_ndarray):
    c_ndarray = np.arange(9).reshape(3,3)
    for i in range(3):
        for j in range(3):
            sum = 0
            for k in range(3):
                aik = a_ndarray[i][k]
                bjk = b_ndarray[k][j]
                sum += aik*bjk
            c_ndarray[i][j] = sum
            
    return c_ndarray

In [34]:
cal_dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [39]:
def cal_dot_v2(a_ndarray, b_ndarray):
    num_i = a_ndarray.shape[0]
    num_j = b_ndarray.shape[1]
    num_k = a_ndarray.shape[1]
    mul_ij = num_i*num_j
    c_ndarray = np.arange(mul_ij).reshape(num_i,num_j)
    for i in range(num_i):
        for j in range(num_j):
            sum = 0
            for k in range(num_k):
                aik = a_ndarray[i][k]
                bjk = b_ndarray[k][j]
                sum += aik*bjk
            c_ndarray[i][j] = sum
            
    return c_ndarray

In [40]:
cal_dot_v2(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

# 行列積が定義されない組み合わせの行列

次に以下のような例を考えます。

$$
D=\left[\begin{array}{c}
-1 & 2 & 3 \\
4 & -5 & 6 \\
\end{array}\right],
E=\left[\begin{array}{c}
-9 & 8 & 7 \\
6 & -5 & 4 \\
\end{array}\right]
$$

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。

## 【問題5】計算が定義されない入力を判定する
問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。この場合、不適切な計算が行われることになります。また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [41]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [42]:
def cal_dot_v3(a_ndarray, b_ndarray):
    while True:     
        if a_ndarray.shape[1] != b_ndarray.shape[0]:
            print('Numpy error: shape mismatch')
            break
        num_i = a_ndarray.shape[0]
        num_j = b_ndarray.shape[1]
        num_k = a_ndarray.shape[1]
        mul_ij = num_i*num_j
        c_ndarray = np.arange(mul_ij).reshape(num_i,num_j)
        for i in range(num_i):
            for j in range(num_j):
                sum = 0
                for k in range(num_k):
                    aik = a_ndarray[i][k]
                    bjk = b_ndarray[k][j]
                    sum += aik*bjk
                c_ndarray[i][j] = sum
            
        return c_ndarray

In [43]:
cal_dot_v3(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [44]:
cal_dot_v3(d_ndarray, e_ndarray)

Numpy error: shape mismatch


## 【問題6】転置
片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [45]:
dt_ndarray = np.transpose(d_ndarray)
et_ndarray = np.transpose(e_ndarray)

In [46]:
#DT・E
np.matmul(dt_ndarray, e_ndarray)

array([[ 33, -28,   9],
       [-48,  41,  -6],
       [  9,  -6,  45]])

In [113]:
#E・DT
np.matmul(e_ndarray, dt_ndarray)

array([[ 46, -34],
       [ -4,  73]])

In [114]:
#ET・D
np.matmul(et_ndarray, d_ndarray)

array([[ 33, -48,   9],
       [-28,  41,  -6],
       [  9,  -6,  45]])

In [115]:
#D・ET
np.matmul(d_ndarray, et_ndarray)

array([[ 46,  -4],
       [-34,  73]])